### ISSUE TITLE
IM69D130 PCB Dimensions for Building a printable enclosure

### ISSUE THREAD

**Issue by hankman13** [Infineon/IM69D130-Microphone-Shield2Go#5]
Hi,

I want to build a small enclosure or holder for the shield2go board. Therefor it would be great to have the dimensions of the board.
I found on the infion website a blend4web viewer, but there is no option to download the 3D modell.

Is there a chance to get the dimeonsions of the board, pin and hole positions? or maybe there exists also a printable enclosure.

Best Regards
Danny

**Comment by HoneyDhandhukia** [comment]
Hi,

Please check the following link for all the 3D Models and PCB Design Data for IM69D130:
https://www.infineon.com/cms/en/product/sensor/mems-microphones/mems-microphones-for-consumer/im69d130/#!boards

Hope this helps!

Best Regards,
Honey
